name: Generic tests

on:
  workflow_call:
    inputs:
      os:
        description: Operating system
        required: true
        type: string

jobs:
  generic_tests:
    name: Generic tests
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo 'Hello, ${{ inputs.os }}!'
          ls
          exit 1
